from pathlib import Path

import streamlit as st
import pandas as pd
import plotly.express as px

BASE_DIR = Path(__file__).resolve().parent
DATA_PATH = BASE_DIR / "data" / "processed" / "customer_segments.csv"

SEGMENT_NAMES = {
    0: "One-Hit Wonders",
    1: "Churned",
    2: "Loyal Core",
    3: "VIP Champions",
}

SEGMENT_COLORS = {
    "VIP Champions": "#2ecc71",
    "Loyal Core": "#3498db",
    "One-Hit Wonders": "#f1c40f",
    "Churned": "#e74c3c",
}

st.set_page_config(page_title="Retail Intelligence Dashboard", layout="wide")

with st.sidebar:
    st.header("About This Dashboard")
    st.write("This interactive dashboard leverages a K-Means Machine Learning model to segment our customer base into distinct, actionable marketing cohorts.")
    st.info("**Business Objective:** Optimize marketing spend, enhance VIP retention, and execute targeted re-engagement campaigns.")

st.title("Retail Customer Segmentation Dashboard")
st.markdown("Transforming raw transactional data into strategic business insights using AI-driven RFM analysis.")
st.markdown("---")

@st.cache_data
def load_data():
    return pd.read_csv(DATA_PATH)

df = load_data()
df["Segment_Name"] = df["Cluster"].map(SEGMENT_NAMES).fillna("Unassigned")


st.header("1. High-Level Business KPIs")
col1, col2, col3, col4 = st.columns(4)

col1.metric("Total Active Customers", f"{len(df):,}")
col2.metric("Total Lifetime Revenue", f"£{df['Monetary'].sum():,.0f}")
col3.metric("Average Order Value (AOV)", f"£{df['AOV'].mean():,.2f}")
col4.metric("Avg. Customer Tenure", f"{df['Tenure'].mean():,.0f} Days")

with st.expander(" Metric Definitions (Click to expand)"):
    st.write("""
    * **Total Active Customers:** The absolute count of unique buyers in the dataset.
    * **Total Lifetime Revenue:** The aggregated monetary value generated by these customers.
    * **Average Order Value (AOV):** The average revenue generated per individual purchase.
    * **Avg. Customer Tenure:** The average duration (in days) between a customer's first and most recent purchase.
    """)

st.markdown("---")

st.header("2. AI-Generated Customer Personas")
st.write("Our unsupervised ML algorithm has identified the following primary customer profiles:")

c1, c2, c3, c4 = st.columns(4)
c1.success("**VIP Champions **\n\nHighly profitable, frequent buyers. They drive our core revenue. \n\n*Action: Reward with exclusive loyalty programs.*")
c2.info("**Loyal Core **\n\nConsistent and stable buyers with solid engagement. \n\n*Action: Deploy cross-selling & upselling strategies.*")
c3.warning("**One-Hit Wonders **\n\nHigh spenders on a single occasion, but low return rate. \n\n*Action: Re-engage with high-value targeted discounts.*")
c4.error("**Churned **\n\nLow monetary value and haven't purchased in a long time. \n\n*Action: Ignore or use low-cost automated drip campaigns.*")

st.markdown("---")

st.header("3. Interactive Visual Analytics")
chart_col1, chart_col2 = st.columns(2)

with chart_col1:
    st.subheader("A. Customer Distribution Matrix")
    segment_counts = df['Segment_Name'].value_counts().reset_index()
    segment_counts.columns = ['Segment_Name', 'Count']
    
    
    fig1 = px.bar(
        segment_counts, 
        x='Count', 
        y='Segment_Name', 
        color='Segment_Name',
        orientation='h',
        color_discrete_map=SEGMENT_COLORS
    )
    fig1.update_layout(showlegend=False, xaxis_title="Total Customers", yaxis_title="")
    st.plotly_chart(fig1, use_container_width=True)
    st.caption(" **Insight:** Hover over the bars to see exact figures. This shows where the bulk of our user base resides.")

with chart_col2:
    st.subheader("B. Value vs. Frequency Engine (Log Scale)")
    
    fig2 = px.scatter(
        df, 
        x='Frequency', 
        y='Monetary', 
        color='Segment_Name',
        hover_data=['CustomerID', 'Recency', 'AOV'], # Added hover details!
        log_x=True, 
        log_y=True,
        opacity=0.7,
        render_mode='svg',
        color_discrete_map=SEGMENT_COLORS
    )
    fig2.update_layout(xaxis_title="Purchase Frequency (Log)", yaxis_title="Total Spend (£) (Log)")
    st.plotly_chart(fig2, use_container_width=True)
    st.caption("🔍 **Insight:** Highly interactive. Try zooming in, or clicking a segment in the legend to isolate specific cohorts. Hover over dots to view specific Customer IDs and their behavior.")
    # --- 8. 3D Customer Universe (Advanced Visualization) ---
st.markdown("---")
st.header("4. 3D Customer Universe (R-F-M Dimensions)")
st.write("A comprehensive 3D view combining Recency, Frequency, and Monetary value.")

fig3d = px.scatter_3d(
    df, 
    x='Recency', 
    y='Frequency', 
    z='Monetary',
    color='Segment_Name',
    hover_name='CustomerID',
    log_y=True, 
    log_z=True,
    opacity=0.7,
    color_discrete_map=SEGMENT_COLORS
)
fig3d.update_layout(margin=dict(l=0, r=0, b=0, t=0), scene=dict(
    xaxis_title='Recency (Days)',
    yaxis_title='Frequency (Log)',
    zaxis_title='Monetary (Log)'
))
st.plotly_chart(fig3d, use_container_width=True)
st.caption("💡 **Tip:** Rotate the 3D space with your mouse to view the clusters from different angles. This perfectly illustrates how the K-Means algorithm mathematically separated the cohorts in a 3D space.")


st.markdown("---")
st.header("5. Cohort Deep-Dive Analysis")
st.write("Understanding the distribution and outliers within each specific segment.")

box_col1, box_col2 = st.columns(2)
with box_col1:
    
    fig_box1 = px.box(df, x="Segment_Name", y="Monetary", color="Segment_Name", log_y=True)
    fig_box1.update_layout(title="Monetary Distribution per Segment", xaxis_title="", yaxis_title="Monetary Value (£)", showlegend=False)
    st.plotly_chart(fig_box1, use_container_width=True)

with box_col2:
    
    fig_box2 = px.box(df, x="Segment_Name", y="Tenure", color="Segment_Name")
    fig_box2.update_layout(title="Customer Tenure Distribution", xaxis_title="", yaxis_title="Tenure (Days)", showlegend=False)
    st.plotly_chart(fig_box2, use_container_width=True)

st.markdown("---")
st.header("6. Marketing Action Center (Data Export)")
st.write("Filter and download specific customer lists for targeted marketing campaigns.")


selected_segment = st.selectbox(" Select Customer Cohort to Export:", df['Segment_Name'].unique())

filtered_df = df[df['Segment_Name'] == selected_segment]
st.dataframe(filtered_df[['CustomerID', 'Recency', 'Frequency', 'Monetary', 'AOV']].head(10), use_container_width=True)
st.write(f"Showing sample of **{len(filtered_df)}** customers in this cohort.")

csv = filtered_df.to_csv(index=False).encode('utf-8')
st.download_button(
    label=f" Download '{selected_segment}' List as CSV",
    data=csv,
    file_name=f"{selected_segment.replace(' ', '_').lower()}_customers.csv",
    mime='text/csv',
)